def build_report(incident):
    return f"""
# 🚨 Incident Report: {incident['incident_id']}

## Summary
A **{incident['severity']}** incident occurred in the **{incident['system']}**, impacting **{incident['impact']}**.

## Timeline
- Start Time: {incident['start_time']}
- End Time: {incident['end_time']}

## Impact Analysis
Users experienced service degradation or downtime.

## Root Cause
{incident['root_cause']}

## Resolution
{incident['resolution']}

## Preventive Measures
{incident['preventive_action']}

---
Generated by IncidentGPT – AI-Powered IT Incident Report Generator
"""
